### ISSUE TITLE
$qProvider.errorOnUnhandledRejections(false)

### ISSUE THREAD

**Issue by Yankovsky** [EPICmynamesBG/angular-http-cancellable#1]
Hi! Great lib. Can you explain what is the purpose of this line?
```
cancellableModule.config(['$qProvider', function($qProvider){
  $qProvider.errorOnUnhandledRejections(false);
}]);
```

**Comment by EPICmynamesBG** [comment]
@Yankovsky If I remember my debugging correctly, this resolves an error that Angular v1.5.9+ throws when used with ui-router. See [this thread](https://github.com/angular-ui/ui-router/issues/2889) for more info.

However, thank you for the note. I'll review that code to see if that is still necessary. :+1:

**Comment by Yankovsky** [comment]
I am not sure that is it responsibility of this lib to take care of ui-router integration. I want to use your lib but I am afraid of such side effects.

**Comment by EPICmynamesBG** [comment]
@Yankovsky I'm looking into removing that now. As I'm digging in, I remembered it's not a ui-router specific issue, but a general Angular issue. I'm attempting to remove it now, but it could take a while. If you have ideas on how to properly fix this, please feel free to contribute via comments or a PR

**Comment by EPICmynamesBG** [comment]
@Yankovsky I believe I've fixed it. If you're willing to checkout the develop branch, it'd be nice to have a tester before pushing the changes to the npm registry

**Comment by Yankovsky** [comment]
Thank you! I'll check it out.

**Comment by Yankovsky** [comment]
I want to integrate your lib with mine https://github.com/Yankovsky/angular-promise-debounce to create ultimate DebouncedCancellableHttp promises :)

**Comment by EPICmynamesBG** [comment]
@Yankovsky Looks pretty cool. Any report on how those updates worked out for you? If it's good, I'll go ahead and merge master and update npm

**Comment by EPICmynamesBG** [comment]
Merged updates into master and published update to npm
